# Generated by Django 3.2 on 2021-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_vehicleimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
