# Generated by Django 3.2 on 2021-04-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210411_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='brand_name',
        ),
    ]
