# Generated by Django 3.2 on 2021-04-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
