# Generated by Django 3.2 on 2021-04-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20210417_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(blank=True, choices=[('VERY NEAT', 'very neat'), ('FAIRLY NEAT', 'fairly neat'), ('NOT NEAT', 'not neat')], max_length=200, null=True),
        ),
    ]
